[tools]
selene = { source = "Roblox/Kampfkarren-selene", version = "0.24.0" }
stylua = { source = "Roblox/JohnnyMorganz-StyLua", version = "0.16.0" }
rotrieve = { source = "Roblox/rotriever", version = "0.5.9" }
lest = { source = "Roblox/lest", version = "3.x.x" }
rbx-aged-cli = { source = "Roblox/rbx-aged-tool", version = "5.x.x" }
