[package]
name = "Signal"
authors = ["Roblox"]
version = "1.0.0"
content_root = "src"
license = "MIT"
files = [ "*", "!*.spec.lua", "!jest.config.lua" ]

[dev_dependencies]
Jest = "github.com/Roblox/jest-roblox@3.2.5"
JestGlobals = "github.com/Roblox/jest-roblox@3.2.5"
